import type { Metadata } from "next";

import "./globals.css";
import { Header } from "./_components/header";
import Footer from "./_components/footer";
import { AppThemeProvider } from "./_components/providers/theme-provider";
import { CssBaseline } from "@mui/material";
import { SnackBarProvider } from "./_components/providers/snackbar-provider";

export const metadata: Metadata = {
  title: "ICS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppThemeProvider>
          <SnackBarProvider>
            <Header />
            {children}
            <Footer />
            <CssBaseline />
          </SnackBarProvider>
        </AppThemeProvider>
      </body>
    </html>
  );
}
